'\" t
.\"     Title: cparted
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 18 March 2011
.\"    Manual: cparted Manual
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "CPARTED" "8" "18 March 2011" "\ \&" "cparted Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
cparted \- Curses based disk partition manipulation program
.SH "SYNOPSIS"
.sp
\fBcparted\fR [\fIOPTION\fR] \fIDEVICE_PATH\fR
.SH "DESCRIPTION"
.sp
\fBcparted\fR is a curses based disk partition manipulation program that aims to replace cfdisk by providing a friendly curses interface with the partition manipulation power of libparted\&. \fBcparted\fR is written in Python, and thus makes use of libparted through pyparted\&.
.SH "OPTIONS"
.PP
\fB\-\-debug\fR
.RS 4
Start
\fBcparted\fR
in debug mode\&. This causes
\fBcparted\fR
to display extended, metadata, and protected partitions, and sets the default unit to sectors\&. This will also prevent the hiding of metadata regions libparted marks as free space\&.
.RE
.SH "BUGS"
.sp
Warning: this software has not been widely tested and has a least a few issues\&.
.sp
Sometimes, when adding a logical partition, two regions of free space will appear next to each other\&. This is bad\&. Do not write to disk if this happens\&. If you do, the partition table will probably be corrupted, and you will have to create a new one\&. One sure way to trigger this bug seems to be creating a logical partition on a disk without any primary partitions\&.
.sp
If you notice additional bugs or have feature requests, create issues for them at https://github\&.com/davekong/cparted/issues\&.
.SH "SEE ALSO"
.sp
\fBparted\fR(8)
.SH "AUTHOR"
.sp
David Campbell <davekong@archlinux\&.us>
